;; Problem 2
;;
;; Each new term in the Fibonacci sequence is
;; generated by adding the previous two terms.
;; By starting with 1 and 2, the first 10 terms
;; will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci
;; sequence whose values do not exceed four
;; million, find the sum of the even-valued
;; terms.

;; implementation

(defn sum-of-even-fibonaccis-below [n]
  (loop [a 1
         b 2
         i 0
         sum 0]
    (if (<= b n)
      (recur b
             (+ a b)
             (+ i 1)
             (if (zero? (mod i 3))
               (+ sum b)
               sum))
      sum)))

;; execution
(sum-of-even-fibonaccis-below 4000000)
